CREATE TABLE salas (
    id SERIAL PRIMARY KEY AUTO_INCREMENT,
    salas VARCHAR(255) NOT NULL,
    descr VARCHAR(255) NOT NULL UNIQUE,
    reservador VARCHAR(100),
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
); 